apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.cluster.instances }}
  {{- with .Values.cluster.imageName }}
  imageName: {{ . }}
  {{- end }}
  storage:
    size: {{ .Values.cluster.storage.size }}
    {{- with .Values.cluster.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- with .Values.cluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.postgresql }}
  postgresql:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.database }}
      owner: {{ .Values.cluster.bootstrap.owner }}
  {{- with .Values.databases }}
  managed:
    roles:
      {{- range . }}
      - name: {{ .name }}
        ensure: present
        login: true
        passwordSecret:
          name: cnpg-role-{{ .name }}
      {{- end }}
  {{- end }}
