{{- range .Values.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  name: {{ .name }}
  owner: {{ .name }}
  cluster:
    name: {{ $.Values.cluster.name }}
{{- end }}
