fullnameOverride: kube-prometheus-stack
namespaceOverride: monitoring

crds:
  enabled: true

defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    windows: false
  disabled:
    KubeCPUOvercommit: true
    CPUThrottlingHigh: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    nodeSelector:
      type: vm
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  admin:
    existingSecret: kube-prometheus-stack-grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsTimezone: Asia/Seoul
  nodeSelector:
    type: vm
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-csi
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt-prod
    path: /grafana
    pathType: Prefix
    hosts:
      - homelab.robinjoon.xyz
    tls:
      - secretName: homelab-robinjoon-xyz-tls
        hosts:
          - homelab.robinjoon.xyz
  grafana.ini:
    server:
      domain: homelab.robinjoon.xyz
      root_url: https://homelab.robinjoon.xyz/grafana
      serve_from_sub_path: true

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kube-state-metrics:
  nodeSelector:
    type: vm
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

prometheusOperator:
  nodeSelector:
    type: vm
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    scrapeInterval: 30s
    evaluationInterval: 30s
    retention: 14d
    retentionSize: 220GiB
    enableAdminAPI: true
    walCompression: true
    externalLabels:
      cluster: homelab-k3s
    nodeSelector:
      type: vm
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 6Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
