grafana:
  ingress:
    path: /
    hosts:
      - grafana.homelab.robinjoon.xyz
    tls:
      - secretName: grafana-homelab-robinjoon-xyz-tls
        hosts:
          - grafana.homelab.robinjoon.xyz
  grafana.ini:
    server:
      domain: grafana.homelab.robinjoon.xyz
      root_url: https://grafana.homelab.robinjoon.xyz
      serve_from_sub_path: false
