nameOverride: "postgresql"
fullnameOverride: "postgresql"
namespaceOverride: "postgresql"

global:
  defaultStorageClass: ""
  storageClass: ""
# standalone 아키텍처
architecture: standalone

metrics:
  enabled: true

auth:
  existingSecret: "postgresql-secret"
  secretKeys:
    adminPasswordKey: postgres-password
    replicationPasswordKey: replication-password

# Primary DB 설정
primary:
  # 메모리 설정
  resources:
    requests:
      cpu: 2000m
      memory: 2048Mi
    limits:
      cpu: 4000m
      memory: 4096Mi
  # 저장소 설정
  persistence:
    storageClass: "longhorn"
    enabled: true
    size: 200Gi
    accessModes:
      - ReadWriteOnce
  # Security Context 설정 (NFS 볼륨 권한 문제 해결)
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
  nodeSelector:
    kubernetes.io/arch: amd64

backup:
  enabled: true
  cronjob:
    schedule: "0 4 * * *"
    successfulJobsHistoryLimit: 3
    storage:
      enabled: true
      storageClass: "nfs-csi"
      size: 600Gi
      accessModes:
        - ReadWriteOnce
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
